name: Pull Request Workflow

on:
  push:
    branches:
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pipenv==11.9.0 # set version due to errors -- TODO debug
          pipenv install --ignore-pipfile

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm install

      - run: pipenv run npx sls deploy --stage dev
